# https://www.youtube.com/watch?v=pYhLEV-sRpY
version: '3'

services:
  # Databse
  db:
    image:  mysql:8
    # container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    # command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - divi-wpsite
  #phpmyadmin
  phpmyadmin:
    # image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - divi-wpsite
      
  # wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - divi-wpsite
networks:
  divi-wpsite:
volumes:
  db_data:



